### ISSUE TITLE
Duda acerca de 3 verso 

### ISSUE THREAD

**Issue by EduRamirez** [EduRamirez/ServomecanismosN3Equipo_4#1]
Al escribir la canción me doy cuenta que alguna palabra podría ser remplazada en el primer verso 3 renglón, la palabra que use es tristesa pero creo que podría ser cambiada por gracia que opinan?

**Comment by Armolv** [comment]
este es mi usuario , intenta agregarme el issue

**Comment by BRYNBRYN** [comment]
Hola

**Comment by EduRamirez** [comment]
Hola Chicos
